<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
namespace Elendev\AppManagerBundle\AppManager\Publisher;
use Elendev\AppManagerBundle\AppManager\AppVersion;
use \Elendev\AppManagerBundle\AppManager\AppEnvironment;
/**
 * Description of Htaccess
 *
 * @author jonas
 */
class Htaccess {
    
    public function generateHtaccess(AppEnvironment $publicEnv, $filePath){
        
        // old htaccess already here : error !
        if(file_exists($filePath) && !$this->getAppAndVersion($filePath)){
            throw new \Exception("htaccess file $filePath wasn't generated by this generator !");
        }
        
        $htaccessContent = 
"#app=" . $publicEnv->getAppVersion()->getApp()->getName() . "
#version=" . $publicEnv->getAppVersion()->getName() ."
<IfModule mod_rewrite.c>
    RewriteEngine On

    #<IfModule mod_vhost_alias.c>
    #    RewriteBase /
    #</IfModule>
    
    RewriteRule ^(.*) " . $publicEnv->getAppVersion()->getPath() . "/web/$1 [QSA,L,DPI]
</IfModule>
        ";
        
        
        if(!file_put_contents($filePath, $htaccessContent)){
            throw new \Exception("Couldn't write new .htaccess file in path " . $htaccessContent);
        }
    }
    
    
    /*
     * return false if it's not a generated .htaccess,
     * return array[app] = app, array[version] = version otherwise
     */
    public function getAppAndVersion($filePath){
        
        if(!file_exists($filePath)){
            return false;
        }
        
        $file = file($filePath, FILE_IGNORE_NEW_LINES);
        
        if(!$file || count($file) < 5){
            return false;
        }
        
        $appLine = $file[0];
        $versionLine = $file[1];
        
        
        if(substr($appLine, 0, 5) != "#app="){
            return false;
        }
        
        if(substr($versionLine, 0, 9) != "#version="){
            return false;
        }
        
        
        return array("app" => substr($appLine, 5), "version" => substr($versionLine, 9));
    }
}

